apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2019-08-27T22:29:19Z
  generation: 4
  labels:
    app: htcondor-generic
  name: htcondor-generic
  namespace: cmst1
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: htcondor-generic
    deploymentconfig: htcondor-generic
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: htcondor-generic
        deploymentconfig: htcondor-generic
    spec:
      containers:
      - image: mapsacosta/htcondor-k8s:sl7_htc8.9.3
        imagePullPolicy: IfNotPresent
        name: htcondor-generic
        ports:
        - containerPort: 9618
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/condor/config.d/01_dfc_collector
          name: collector-configmap
          subPath: 01_dfc_collector
        - mountPath: /etc/condor/config.d/02_dfc_gsi
          name: gsi-configmap
          subPath: 02_dfc_gsi
        - mountPath: /etc/condor/config.d/config.d.quota/05_dfc_negotiator_slot
          name: neg-configmap
          subPath: 05_dfc_negotiator_slot
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: 01-htcondor-collector
        name: collector-configmap
      - configMap:
          defaultMode: 420
          name: 02-htcondor-gsi
        name: gsi-configmap
      - configMap:
          defaultMode: 420
          name: 05-htcondor-negotiator-quota
        name: neg-configmap
  test: false
