apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: okd-ce
  name: okd-ce
  namespace: cmst1
spec:
  ports:
  - name: condor-ce
    port: 9618
    protocol: TCP
    targetPort: 9618
  selector:
    app: okd-ce
    deploymentconfig: okd-ce
  externalIPs:
  - 131.225.205.135
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
